-- =============================================================================
-- Seed: machines
-- Повний набір виробничого парку Dyz-Art. Усі 15 колонок заповнюються тут;
-- там, де значення не задане — NULL.
-- =============================================================================

INSERT INTO machines
    (id, name, type, operation,
     max_sheet_mm, min_sheet_mm,
     colors, min_run, max_run,
     max_stock_gsm, min_stock_gsm,
     max_pages, min_pages,
     supported_finishes,
     notes)
VALUES
    ('heidelberg_sm52',
     'Heidelberg Speedmaster SM 52',
     'offset_press', 'offset_printing',
     ARRAY[360, 520], ARRAY[100, 150],
     4, 100, NULL, 400, 60,
     NULL, NULL,
     NULL,
     'Основна аркушева офсетна машина. CMYK + Pantone.'),

    ('heidelberg_sm74',
     'Heidelberg Speedmaster SM 74',
     'offset_press', 'offset_printing',
     ARRAY[530, 740], ARRAY[200, 280],
     5, 500, NULL, 400, 60,
     NULL, NULL,
     NULL,
     '5-фарбова машина. CMYK + 1 Pantone або лак inline.'),

    ('hp_indigo_12000',
     'HP Indigo 12000',
     'digital_press', 'digital_printing',
     ARRAY[480, 660], ARRAY[100, 148],
     7, NULL, 1000, 350, 60,
     NULL, NULL,
     NULL,
     'Цифровий друк для малих тиражів. Персоналізація.'),

    ('laminator_autobond',
     'Autobond Mini 76 T',
     'laminator', 'lamination',
     ARRAY[760, 1060], ARRAY[200, 280],
     NULL, NULL, NULL, 400, NULL,
     NULL, NULL,
     ARRAY['gloss_lamination','matte_lamination','soft_touch_lamination'],
     'Термоламінатор для аркушевої продукції.'),

    ('uv_coater_dk',
     'DK-1650 UV Coater',
     'uv_coater', 'uv_varnishing',
     ARRAY[650, 1050], NULL,
     NULL, NULL, NULL, 400, NULL,
     NULL, NULL,
     ARRAY['uv_varnish'],
     'Суцільне та вибіркове УФ-лакування.'),

    ('foil_stamper_kama',
     'KAMA ProCut 74',
     'foil_stamper', 'hot_foil_stamping',
     ARRAY[530, 740], NULL,
     NULL, 100, NULL, 450, NULL,
     NULL, NULL,
     NULL,
     'Гаряче тиснення фольгою. Потрібне кліше (виготовлення 3-5 днів).'),

    ('die_cutter_bobst',
     'BOBST SP 76 E',
     'die_cutter', 'die_cutting',
     ARRAY[760, 1060], NULL,
     NULL, 200, NULL, 800, NULL,
     NULL, NULL,
     NULL,
     'Висічна машина. Потрібен висічний штамп (виготовлення 1-2 дні).'),

    ('creaser_morgana',
     'Morgana AutoCreaser Pro 50',
     'creaser', 'creasing',
     ARRAY[350, 500], NULL,
     NULL, NULL, NULL, 400, NULL,
     NULL, NULL,
     NULL,
     'Автоматична біговка.'),

    ('card_cutter_polar',
     'POLAR 115 + Corner Rounder',
     'guillotine_cutter', 'card_cutting',
     ARRAY[1150, 1150], NULL,
     NULL, NULL, NULL, NULL, NULL,
     NULL, NULL,
     NULL,
     'Різання карт + закруглення кутів R3/R4.'),

    ('saddle_stitcher_muller',
     'Müller Martini BRAVO',
     'saddle_stitcher', 'saddle_stitching',
     NULL, NULL,
     NULL, NULL, NULL, 170, NULL,
     96, 8,
     NULL,
     'Зшивання скобою. Мінімум 8 сторінок.'),

    ('perfect_binder_horizon',
     'Horizon BQ-270',
     'perfect_binder', 'perfect_binding',
     NULL, NULL,
     NULL, NULL, NULL, 170, NULL,
     500, 32,
     NULL,
     'Клейове скріплення для книг і товстих правил.'),

    ('xerox_versant_280',
     'Xerox Versant 280 Press',
     'digital_press', 'digital_printing',
     ARRAY[330, 660], ARRAY[98, 148],
     4, 1, 1500, 400, 52,
     NULL, NULL,
     NULL,
     'Цифровий друк для персоналізації, прототипів і коротких серій.'),

    ('komori_lithrone_g40',
     'Komori Lithrone G40',
     'offset_press', 'offset_printing',
     ARRAY[720, 1030], ARRAY[210, 297],
     6, 1000, NULL, 450, 70,
     NULL, NULL,
     NULL,
     'Високопродуктивний офсет для великих тиражів коробки та обкладинок.'),

    ('screen_truepress_jet',
     'SCREEN Truepress Jet L350',
     'inkjet_press', 'digital_printing',
     ARRAY[350, 1000], ARRAY[120, 200],
     4, 1, 800, 250, 60,
     NULL, NULL,
     NULL,
     'Струменевий друк для змінних даних та швидких повторюваних запусків.'),

    ('guowang_1060',
     'Guowang C1060',
     'die_cutter', 'die_cutting',
     ARRAY[760, 1060], ARRAY[200, 280],
     NULL, 300, NULL, 900, 150,
     NULL, NULL,
     NULL,
     'Автоматична висічка картону та мікрогофри для коробкових заготовок.'),

    ('mbo_k80',
     'MBO K80',
     'folder', 'creasing',
     ARRAY[800, 1200], ARRAY[148, 210],
     NULL, 100, NULL, 250, 60,
     NULL, NULL,
     NULL,
     'Фальцювально-бігувальна лінія для інструкцій, вкладок і буклетів.'),

    ('kolbus_da260',
     'Kolbus DA 260',
     'rigid_box_line', 'box_assembly',
     NULL, NULL,
     NULL, 200, NULL, NULL, NULL,
     NULL, NULL,
     NULL,
     'Лінія автоматичного складання жорстких коробок типу кришка-дно.'),

    ('stahlfolder_th82',
     'Stahlfolder TH 82',
     'folder', 'saddle_stitching',
     ARRAY[820, 1200], ARRAY[100, 140],
     NULL, 200, NULL, 170, 60,
     NULL, NULL,
     NULL,
     'Підготовка зошитів перед скобою, стабільна робота на тонких паперах.'),

    ('heidelberg_pm52_2',
     'Аркушева двохкольорова машина Heidelberg PM 52/2',
     'offset_press', 'offset_printing',
     ARRAY[360, 520], ARRAY[100, 150],
     2, 200, NULL, 350, 60,
     NULL, NULL,
     NULL,
     'двокольоровий офсет для коротких/середніх тиражів'),

    ('ml_1200_die_cutter',
     'Висікальна машина ML 1200',
     'die_cutter', 'die_cutting',
     ARRAY[1200, 1200], ARRAY[250, 350],
     NULL, 200, NULL, 1200, 150,
     NULL, NULL,
     NULL,
     'тигельна/плоска висічка картону та мікрогофри'),

    ('embosser_yw750a',
     'Ембоссер YW-750A',
     'embosser', 'embossing',
     ARRAY[750, 750], ARRAY[100, 140],
     NULL, 100, NULL, 450, 150,
     NULL, NULL,
     NULL,
     'рельєфне тиснення (конгрев/деборг)'),

    ('kasher_700x1000',
     'Кашерувальний станок до 700x1000',
     'laminator', 'chipboard_laminating',
     ARRAY[700, 1000], ARRAY[210, 297],
     NULL, 200, NULL, NULL, NULL,
     NULL, NULL,
     NULL,
     'каширування покривного аркуша на основу'),

    ('yb1100bb_casher',
     'Кашировальна машина YB1100 BB',
     'laminator', 'chipboard_laminating',
     ARRAY[1100, 1100], ARRAY[250, 350],
     NULL, 300, NULL, NULL, NULL,
     NULL, NULL,
     NULL,
     'автоматичне каширування для коробкових заготовок'),

    ('xy750a_gluer',
     'Клеємазальна машина XY-750A',
     'gluer', 'box_assembly',
     ARRAY[750, 750], ARRAY[120, 200],
     NULL, 100, NULL, NULL, NULL,
     NULL, NULL,
     NULL,
     'нанесення клею перед склеюванням'),

    ('tg40_box_maker',
     'Машина для виготовлення картонних коробок TG-40',
     'folder_gluer', 'box_assembly',
     NULL, NULL,
     NULL, 300, NULL, NULL, NULL,
     NULL, NULL,
     NULL,
     'формування та склеювання картонних коробок'),

    ('mt1040_card_maker',
     'Машина для виготовлення карточок MT-1040',
     'card_line', 'card_cutting',
     ARRAY[1040, 1040], ARRAY[200, 280],
     NULL, 500, NULL, 400, 250,
     NULL, NULL,
     NULL,
     'лінія для виробництва ігрових/візиткових карт'),

    ('crosland_tya_die',
     'Машина для висікання Crosland TYA',
     'die_cutter', 'die_cutting',
     ARRAY[720, 1020], ARRAY[200, 280],
     NULL, 200, NULL, 800, 150,
     NULL, NULL,
     NULL,
     'автоматична висічка штампом'),

    ('mt_rc21_corner_rounder',
     'Машина для заокруглення кутів MT-RC21',
     'corner_rounder', 'card_cutting',
     ARRAY[210, 297], ARRAY[40, 60],
     NULL, 1000, NULL, 400, 200,
     NULL, NULL,
     NULL,
     'заокруглення кутів карт R3/R4'),

    ('sw1000_creaser',
     'Машина для прорізання канавок SW1000',
     'creaser', 'creasing',
     ARRAY[1000, 1000], ARRAY[200, 280],
     NULL, 200, NULL, 600, 200,
     NULL, NULL,
     NULL,
     'біговка і канавки згину'),

    ('thermal_laminator_semiauto',
     'Напівавтоматичний термальний ламінатор',
     'laminator', 'lamination',
     ARRAY[700, 1000], ARRAY[210, 297],
     NULL, 50, NULL, 450, 80,
     NULL, NULL,
     NULL,
     'Матова/глянцева плівка на задрукований аркуш; робоча ширина до 700 мм.'),

    ('tymb_cnc_foil_press',
     'Позолочений тигельний прес TYMB CNC',
     'foil_stamper', 'hot_foil_stamping',
     ARRAY[750, 1050], ARRAY[210, 297],
     NULL, 100, NULL, 600, 150,
     NULL, NULL,
     NULL,
     'гаряче тиснення фольгою, керування CNC'),

    ('heidelberg_sm102_2',
     'Офсетна друкарська машина Heidelberg SM 102-2',
     'offset_press', 'offset_printing',
     ARRAY[1040, 730], ARRAY[210, 297],
     2, 500, NULL, 450, 70,
     NULL, NULL,
     NULL,
     'Формат листа до 1040×730 мм; основний офсет для коробкових покривних аркушів.'),

    ('wj_pa6090en_silkscreen',
     'Шовкотрафаретний напівавтомат WJ-PA6090EN',
     'screen_printing_press', 'uv_varnishing',
     ARRAY[600, 900], ARRAY[120, 180],
     1, 50, NULL, 600, 120,
     NULL, NULL,
     NULL,
     'УФ-лакування (шовкотрафарет); без офсетного та інталіо-друку на цьому вузлі.'),

    ('wj_uv7508_tunnel',
     'Сушильна тунельна установка WJ-UV7508',
     'uv_dryer', 'uv_varnishing',
     NULL, NULL,
     NULL, NULL, NULL, NULL, NULL,
     NULL, NULL,
     NULL,
     'Сушіння відтисків після УФ-лаку; працює в парі з WJ-PA6090EN.'),

    ('roll_sheeter_dyz',
     'Рулонорізальна машина (флотування)',
     'sheeter', 'roll_slitting',
     ARRAY[1500, 1050], ARRAY[400, 300],
     NULL, NULL, NULL, NULL, NULL,
     NULL, NULL,
     NULL,
     'Порізка рулонів паперу, картону та двошарового гофрокартону на листи. Листовий матеріал — етап не потрібен.'),

    ('corner_taper_automatic',
     'Машина для обклейки кутиків скотчем',
     'taper', 'corner_taping',
     NULL, NULL,
     NULL, NULL, NULL, NULL, NULL,
     NULL, NULL,
     NULL,
     'Фіксація кутів жорсткої коробки.'),

    ('gofo_line_eb_1050',
     'Гофроагрегат (тришаровий гофрокартон, ширина 1050 мм)',
     'corrugator', 'corrugating',
     ARRAY[1050, 2500], NULL,
     NULL, NULL, NULL, NULL, NULL,
     NULL, NULL,
     NULL,
     'Профіль E, тип B; виробництво трьохшарового гофрокартону.'),

    ('gofo_two_layer_line',
     'Гофроагрегат (рулони 2-х шару г/к, гофровалі №1 та №2)',
     'corrugator', 'corrugating',
     ARRAY[1200, 3000], NULL,
     NULL, NULL, NULL, NULL, NULL,
     NULL, NULL,
     NULL,
     'Двошаровий гофрокартон з верхніми гофровалами №1 та №2.'),

    ('tymb_die_press',
     'Тигельний прес висічний / СТ-315В',
     'die_cutter', 'die_cutting',
     ARRAY[800, 1100], ARRAY[200, 280],
     NULL, 100, NULL, 1200, 150,
     NULL, NULL,
     NULL,
     'Висічка тиглем; альтернатива/доповнення до аркушевої висічки.'),

    ('tg40_box_wrapper',
     'Машина для склеювання картонних коробок (обклейка)',
     'folder_gluer', 'box_assembly',
     ARRAY[800, 1200], ARRAY[200, 280],
     NULL, 200, NULL, NULL, NULL,
     NULL, NULL,
     NULL,
     'Обклейка коробки друкарським листом / формування короба.');
