-- =============================================================================
-- Seed: stock_items — точні позиції зі складу (dyz_art_stock.csv)
-- supply_form: roll — один лінійний розмір у назві (рулон / ширина);
--   sheet — два розміри (NNNхMMM); web — рулонний матеріал WEB у назві; film — плівка.
-- paper_id прив'язує позицію до канонічного типу в таблиці papers.
-- =============================================================================

INSERT INTO stock_items (stock_no, name, for_use, supply_form, notes, paper_id)
VALUES
    (1,   'Allyking Cream GC2 215 1 050 Картон целюлозний  c1s',            NULL,                    'roll',  NULL,                 'coated_250'),
    (2,   'Allyking Cream GC2 215 560х285 Картон целюлозний  c1s',          NULL,                    'sheet', NULL,                 'coated_250'),
    (3,   'Allyking Cream GC2 215 600 Картон целюлозний  c1s',              NULL,                    'roll',  NULL,                 'coated_250'),
    (4,   'Allyking Cream GC2 215 640 Картон целюлозний  c1s',              NULL,                    'roll',  NULL,                 'coated_250'),
    (5,   'Allyking Cream GC2 215 640х900 Картон целюлозний  c1s',          NULL,                    'sheet', NULL,                 'coated_250'),
    (47,  'CTD Глос 170 650х920 Папір крейдований глянцевий',               'коробка',               'sheet', 'для обклейка + друк','coated_170'),
    (48,  'CTD Глос 400 640х175 Папір крейдований глянцевий',               'коробка',               'sheet', 'для обклейка + друк','coated_400'),
    (49,  'CTD Сілк 350 750х505 Папір крейдований матовий',                 NULL,                    'sheet', NULL,                 'coated_350'),
    (50,  'CTD Сілк WEB 170 450х646 Папір крейдований матовий',             NULL,                    'web',   NULL,                 'coated_170'),
    (55,  'Euca Pro High Bulk C2S Art Board 300 640х900 Картон целюлозний  c2s',  NULL,              'sheet', NULL,                 'coated_300'),
    (56,  'Euca Pro High Bulk C2S Art Board 300 700х1 000 Картон целюлозний  c2s', NULL,             'sheet', NULL,                 'coated_300'),
    (57,  'Euca Pro High Bulk C2S Art Board 320 640х900 Картон целюлозний  c2s',  NULL,              'sheet', NULL,                 'coated_320'),
    (58,  'Euca Pro High Bulk C2S Art Board 320 700х139 Картон целюлозний  c2s',  NULL,              'sheet', NULL,                 'coated_320'),
    (59,  'Euca Pro High Bulk C2S Art Board 320 720х1 040 Картон целюлозний  c2s', NULL,             'sheet', NULL,                 'coated_320'),
    (90,  'Hi-Kote gloss 250 145х420 Папір крейдований глянцевий',          'карти',                 'sheet', NULL,                 'coated_250'),
    (91,  'Hi-Kote gloss 250 160х900 Картон целюлозний  c1s',               'карти',                 'sheet', NULL,                 'coated_250'),
    (92,  'Hi-Kote gloss 250 300х250 Папір крейдований глянцевий',          'карти',                 'sheet', NULL,                 'coated_250'),
    (93,  'Hi-Kote gloss 250 700х1 000 Папір крейдований глянцевий',        'карти',                 'sheet', NULL,                 'coated_250'),
    (94,  'Hi-Kote gloss 300 640х900 Папір крейдований глянцевий',          'карти',                 'sheet', NULL,                 'playing_card_310'),
    (95,  'Hi-Kote gloss 300 700х1 000 Папір крейдований глянцевий',        'карти',                 'sheet', NULL,                 'playing_card_310'),
    (96,  'Hi-Kote gloss 350 700х500 Папір крейдований глянцевий',          'карти',                 'sheet', NULL,                 'playing_card_310'),
    (97,  'Hi-Kote matt 300 640х450 Папір крейдований матовий',             'карти',                 'sheet', NULL,                 'playing_card_310'),
    (98,  'Hi-Kote matt 300 700х200 Папір крейдований матовий',             'карти',                 'sheet', NULL,                 'playing_card_310'),
    (99,  'Hi-Kote matt 350 190х425 Папір крейдований матовий',             'карти',                 'sheet', NULL,                 'playing_card_310'),
    (100, 'Hi-Kote matt 350 690х1 020 Папір крейдований матовий',           'карти',                 'sheet', NULL,                 'playing_card_310'),
    (101, 'Hi-Kote matt 350 700х1 000 Папір крейдований матовий',           'карти',                 'sheet', NULL,                 'playing_card_310'),
    (102, 'Ilim 120 700 Папір офсетний',                                    NULL,                    'roll',  NULL,                 'offset_120'),
    (103, 'Ilim 120 840 Папір офсетний',                                    NULL,                    'roll',  NULL,                 'offset_120'),
    (104, 'IQ Прінт 120 420х650 Папір офсетний',                            NULL,                    'sheet', NULL,                 'offset_120'),
    (105, 'IQ Прінт 250 700х1 000 Папір офсетний',                          NULL,                    'sheet', NULL,                 'offset_250'),
    (106, 'Kraft board 280 700 Крафт білий',                                NULL,                    'roll',  NULL,                 'kraft_white_280'),
    (107, 'Kraftliner Brown 170 200х820 Крафт бурий',                       NULL,                    'sheet', NULL,                 'kraftliner_brown_170'),
    (108, 'Kraftliner Brown 170 305х1 000 Крафт бурий',                     NULL,                    'sheet', NULL,                 'kraftliner_brown_170'),
    (109, 'Kraftliner Brown 170 365х200 Крафт бурий',                       NULL,                    'sheet', NULL,                 'kraftliner_brown_170'),
    (153, 'Peony C2S ART PAPER 115 640х900 Папір крейдований глянцевий',    'інструкція',            'sheet', NULL,                 'coated_115'),
    (154, 'Peony C2S ART PAPER 115 700х1 000 Папір крейдований глянцевий',  'інструкція',            'sheet', NULL,                 'coated_115'),
    (162, 'PRIMA BULKY gloss 130 640х900 Папір крейдований глянцевий',      'коробка',               'sheet', NULL,                 'coated_130'),
    (163, 'PRIMA BULKY gloss 130 700х1 000 Папір крейдований глянцевий',    'коробка',               'sheet', NULL,                 'coated_130'),
    (164, 'PRIMA BULKY gloss 150 700х1 000 Папір крейдований глянцевий',    'коробка, інструкція, поле', 'sheet', NULL,             'coated_150'),
    (165, 'PRIMA BULKY gloss 150 700х220 Папір крейдований глянцевий',      'коробка, інструкція, поле', 'sheet', NULL,             'coated_150'),
    (166, 'PRIMA BULKY gloss 170 219х1 000 Папір крейдований глянцевий',    'коробка, поле',         'sheet', NULL,                 'coated_170'),
    (167, 'PRIMA BULKY gloss 170 375х165 Папір крейдований глянцевий',      'коробка, поле',         'sheet', NULL,                 'coated_170'),
    (168, 'PRIMA BULKY gloss 170 450х147 Папір крейдований глянцевий',      'коробка, поле',         'sheet', NULL,                 'coated_170'),
    (169, 'PRIMA BULKY gloss 170 640х158 Папір крейдований глянцевий',      'коробка, поле',         'sheet', NULL,                 'coated_170'),
    (170, 'PRIMA BULKY gloss 170 640х190 Папір крейдований глянцевий',      'коробка, поле',         'sheet', NULL,                 'coated_170'),
    (171, 'PRIMA BULKY gloss 170 640х900 Папір крейдований глянцевий',      'коробка, поле',         'sheet', NULL,                 'coated_170'),
    (172, 'PRIMA BULKY gloss 170 700х220 Папір крейдований глянцевий',      'коробка, поле',         'sheet', NULL,                 'coated_170'),
    (173, 'PRIMA BULKY gloss 250 640х900 Папір крейдований глянцевий',      'карти',                 'sheet', NULL,                 'coated_250'),
    (174, 'PRIMA BULKY gloss 250 700х1 000 Папір крейдований глянцевий',    'карти',                 'sheet', NULL,                 'coated_250'),
    (175, 'PRIMA BULKY gloss 300 116х900 Папір крейдований глянцевий',      'карти',                 'sheet', NULL,                 'playing_card_310'),
    (176, 'PRIMA BULKY gloss 300 640х900 Папір крейдований глянцевий',      'карти',                 'sheet', NULL,                 'playing_card_310'),
    (177, 'PRIMA BULKY gloss 300 700х1 000 Папір крейдований глянцевий',    'карти',                 'sheet', NULL,                 'playing_card_310'),
    (178, 'PRIMA BULKY gloss 350 640х900 Папір крейдований глянцевий',      'карти',                 'sheet', NULL,                 'playing_card_310'),
    (179, 'PRIMA BULKY gloss 350 700х1 000 Папір крейдований глянцевий',    'карти',                 'sheet', NULL,                 'playing_card_310'),
    (180, 'PRIMA BULKY gloss 90 640х900 Папір крейдований глянцевий',       NULL,                    'sheet', NULL,                 'coated_90'),
    (181, 'PRIMA BULKY silk 250 700х1 000 Папір крейдований матовий',       'карти',                 'sheet', NULL,                 'coated_250'),
    (182, 'PRIMA BULKY silk 300 640х900 Папір крейдований матовий',         'карти',                 'sheet', NULL,                 'playing_card_310'),
    (183, 'PRIMA BULKY silk 350 640х450 Папір крейдований матовий',         'карти',                 'sheet', NULL,                 'playing_card_310'),
    (184, 'PRIMA BULKY silk 350 700х1 000 Папір крейдований матовий',       'карти',                 'sheet', NULL,                 'playing_card_310'),
    (199, 'SBB 160 1 050х750 Картон целюлозний  c1s',                       'коробка',               'sheet', 'обклейка + друк',    'coated_160'),
    (200, 'SBB 160 1 260 Картон целюлозний  c1s',                           'коробка',               'roll',  'обклейка + друк',    'coated_160'),
    (201, 'SBB 160 135х490 Картон целюлозний  c1s',                         'коробка',               'sheet', 'обклейка + друк',    'coated_160'),
    (202, 'SBB 160 155х720 Картон целюлозний  c1s',                         'коробка',               'sheet', 'обклейка + друк',    'coated_160'),
    (203, 'SBB 160 195х720 Картон целюлозний  c1s',                         'коробка',               'sheet', 'обклейка + друк',    'coated_160'),
    (204, 'SBB 160 210х448 Картон целюлозний  c1s',                         'коробка',               'sheet', 'обклейка + друк',    'coated_160'),
    (205, 'SBB 160 210х880 Картон целюлозний  c1s',                         'коробка',               'sheet', 'обклейка + друк',    'coated_160'),
    (206, 'SBB 160 220х555 Картон целюлозний  c1s',                         'коробка',               'sheet', 'обклейка + друк',    'coated_160'),
    (207, 'SBB 160 250х550 Картон целюлозний  c1s',                         'коробка',               'sheet', 'обклейка + друк',    'coated_160'),
    (208, 'SBB 160 275х550 Картон целюлозний  c1s',                         'коробка',               'sheet', 'обклейка + друк',    'coated_160'),
    (209, 'SBB 160 275х750 Картон целюлозний  c1s',                         'коробка',               'sheet', 'обклейка + друк',    'coated_160'),
    (220, 'Smurfit Kappa Grey board 1.25 790 700х1 000 Картон палітурний',  'коробка основа',        'sheet', NULL,                 'grey_chipboard_1500'),
    (221, 'Smurfit Kappa Grey board 1.5 945 700х1 000 Картон палітурний',   'коробка основа',        'sheet', NULL,                 'grey_chipboard_1500'),
    (222, 'Smurfit Kappa Grey board 2.0 1 260 700х1 000 Картон палітурний', 'коробка основа',        'sheet', NULL,                 'grey_chipboard_1500'),
    (223, 'Smurfit Kappa Grey board 3.0 1 890 700х1 000 Картон палітурний', 'коробка основа',        'sheet', NULL,                 'grey_chipboard_2000'),
    (224, 'Smurfit Kappa Grey board 3.0 1 890 920х1 050 Картон палітурний', 'коробка основа',        'sheet', NULL,                 'grey_chipboard_2000'),
    (225, 'SOLID BLACK BOARD PASTED 1.25 840 750х1 050 Картон палітурний',  'коробка основа',        'sheet', NULL,                 'grey_chipboard_2000'),
    (226, 'SOLID BLACK BOARD PASTED 1.5 1 005 1 000х1 050 Картон палітурний', 'коробка основа',      'sheet', NULL,                 'grey_chipboard_2000'),
    (234, 'Testliner white top 130 600 Папір для гофрування',               NULL,                    'roll',  NULL,                 'liner_white_130'),
    (235, 'Topliner C1S 100 240х355 Папір для гофрування',                  NULL,                    'sheet', NULL,                 'liner_topliner_100'),
    (236, 'Topliner C1S 100 480х720 Папір для гофрування',                  NULL,                    'sheet', NULL,                 'liner_topliner_100'),
    (237, 'Topliner C1S 100 980 Папір для гофрування',                      NULL,                    'roll',  NULL,                 'liner_topliner_100'),
    (238, 'Topliner C1S 135 725 Картон целюлозний  c1s',                    NULL,                    'roll',  NULL,                 'liner_topliner_135'),
    (239, 'Topliner C1S 160 1 060 Картон целюлозний  c1s',                  NULL,                    'roll',  NULL,                 'liner_topliner_160'),
    (240, 'Topliner C1S 200 140х1 020 Картон целюлозний  c1s',              NULL,                    'sheet', NULL,                 'liner_topliner_200'),
    (241, 'Topliner C1S 200 720х1 020 Картон целюлозний  c1s',              NULL,                    'sheet', NULL,                 'liner_topliner_200'),
    (319, 'Давальницька плівка ламінаційна матова  320',                    NULL,                    'film',  NULL,                 NULL),
    (320, 'Давальницька плівка ламінаційна матова440',                      NULL,                    'film',  NULL,                 NULL);
