-- =============================================================================
-- Seed: operations — каталог технологічних операцій
-- step — порядок у типовому циклі (довідково); конкретні маршрути див. у
-- seeds/08_product_type_routes.sql.
-- =============================================================================

INSERT INTO operations
    (id, name, step, description, required_for, compatible_materials,
     duration_config, output_text, min_run, max_run)
VALUES
    ('prepress',
     'Препрес / допечатна підготовка', 1,
     'Накладання макетів на креслення, узгодження з замовником; після погодження — вивід пластин на друк.',
     ARRAY['all'], NULL,
     '{"duration_hours_per_job": 2}',
     'затверджені пластини / готовність до друку', NULL, NULL),

    ('roll_slitting',
     'Флотування (рулон → лист)', 2,
     'Порізка картону чи паперу з рулонів на листи. Якщо матеріал уже листовий — етап не виконується. Обладнання: рулонорізальна лінія для паперу, картону та двошарового гофрокартону.',
     ARRAY['rigid_box','folding_box','box_cover','card_deck','info_leaflet','game_board'], NULL,
     '{"duration_hours_per_1000_sheets": 0.2}',
     'листи заданого формату', NULL, NULL),

    ('sheet_format_cutting',
     'Порізка на формат друку', 2,
     'Порізка листового матеріалу на робочий формат під друкарську машину.',
     ARRAY['rigid_box','folding_box','box_cover','card_deck','info_leaflet','rulebook','game_board'], NULL,
     '{"duration_hours_per_1000_sheets": 0.15}',
     'лист у форматі під друк', NULL, NULL),

    ('offset_printing',
     'Друк (офсет)', 2,
     'Нанесення фарбовідбитків на матеріал. Офсетна друкарська машина Heidelberg SM 102-2; формат листа до 1040×730 мм.',
     ARRAY['box_cover','card_deck','info_leaflet','rulebook','insert','game_board'],
     ARRAY['coated_400','coated_350','coated_320','coated_300','coated_250','coated_170','coated_160',
           'coated_150','coated_130','coated_115','coated_90',
           'offset_90','offset_120','offset_250','playing_card_310',
           'kraft_white_280','kraftliner_brown_170','liner_white_130',
           'liner_topliner_100','liner_topliner_135','liner_topliner_160','liner_topliner_200'],
     '{"duration_hours_per_1000_sheets": 0.5}',
     'задрукований аркуш', 500, NULL),

    ('digital_printing',
     'Цифровий друк', 2,
     'HP Indigo або Xerox — для малих тиражів і персоналізації',
     ARRAY['box_cover','card_deck','info_leaflet','rulebook'],
     ARRAY['coated_400','coated_350','coated_320','coated_300','coated_250','coated_170','coated_160',
           'coated_150','coated_130','coated_115','coated_90',
           'offset_90','offset_120','offset_250','playing_card_310','kraft_white_280'],
     '{"duration_hours_per_1000_sheets": 1.5}',
     'задрукований аркуш', NULL, 499),

    ('lamination',
     'Ламінування', 3,
     'Нанесення плівки на задрукований аркуш (матова / глянцева). Ламінатор; типова максимальна ширина робочого поля 700 мм (див. обмеження в KB). Для колод карт — ламінація аркуша перед різанням на колоди.',
     ARRAY['box_cover','card_deck','info_leaflet','card_deck_cover','premium_insert','game_board'],
     ARRAY['coated_400','coated_350','coated_320','coated_300','coated_250','coated_170','coated_160',
           'coated_150','coated_130','coated_115','coated_90',
           'offset_120','offset_250','playing_card_310'],
     '{"duration_hours_per_1000_sheets": 0.4}',
     'ламінований аркуш', NULL, NULL),

    ('uv_varnishing',
     'УФ-лакування', 4,
     'Шовкотрафаретний напівавтомат WJ-PA6090EN; сушіння — тунельна установка WJ-UV7508. Окремо від офсетного та інталіо-друку на цьому вузлі.',
     ARRAY['premium_box_cover','card_deck','info_leaflet','rigid_box','game_board'],
     ARRAY['coated_400','coated_350','coated_320','coated_300','coated_250','coated_170','coated_160',
           'coated_150','coated_130','coated_115','playing_card_310'],
     '{"duration_hours_per_1000_sheets": 0.3}',
     'аркуш з УФ-лаком', NULL, NULL),

    ('corrugating',
     'Гофрування', 3,
     'Виготовлення гофрокартону (профіль E, тип B). Гофроагрегат шириною до 1050 мм; окремо — лінія для двошарового г/к з верхніми гофровалами №1 та №2. Застосовується, якщо коробка з гофрооснови.',
     ARRAY['folding_box'], NULL,
     '{"duration_hours_per_1000_sheets": 0.5}',
     'гофрокартон / заготовка гофри', NULL, NULL),

    ('hot_foil_stamping',
     'Гаряче тиснення фольгою', 5,
     'Нанесення металевої або голографічної фольги нагрітим кліше. За потреби дизайну (преміум-коробка).',
     ARRAY['premium_box_cover'],
     ARRAY['coated_400','coated_350','coated_320','coated_300','coated_250','coated_170','coated_160',
           'coated_150','coated_130'],
     '{"duration_hours_per_1000_sheets": 1.0}',
     'аркуш з фольгою', NULL, NULL),

    ('embossing',
     'Рельєфне тиснення', 5,
     'Формування рельєфу (конгрев — опуклий / деборг — увігнутий) без фарби',
     ARRAY['premium_box_cover'],
     ARRAY['coated_400','coated_350','coated_320','coated_300','coated_250','coated_170','coated_160',
           'coated_150','coated_130'],
     '{"duration_hours_per_1000_sheets": 0.8}',
     'аркуш з рельєфом', NULL, NULL),

    ('chipboard_laminating',
     'Кашировка (кашировання)', 7,
     'Приклейка друкованих листів до палітурного картону або гофрооснови. Кашировальна машина YB1100 BB.',
     ARRAY['rigid_box','game_board'],
     ARRAY['grey_chipboard_1500','grey_chipboard_2000'],
     '{"duration_hours_per_1000_units": 2.0}',
     'заготовка після каширування', NULL, NULL),

    ('die_cutting',
     'Висічка (вирубка)', 6,
     'Формування заготовки тиглем і висічним штампом. Обладнання: тигельний прес висічний або СТ-315В; машина для висікання Crosland TYA.',
     ARRAY['box_blank','card_blank','insert_blank','game_board'],
     ARRAY['coated_400','coated_350','coated_320','coated_300','coated_250','coated_170','coated_160',
           'coated_150','coated_130','coated_115','coated_90',
           'playing_card_310','grey_chipboard_1500','grey_chipboard_2000',
           'offset_120','offset_250','kraft_white_280',
           'liner_topliner_100','liner_topliner_135','liner_topliner_160','liner_topliner_200'],
     '{"duration_hours_per_1000_sheets": 0.6}',
     'заготовка після висічки', NULL, NULL),

    ('creasing',
     'Рицовка / біговка', 6,
     'Проріз (канавка) палітурного картону або лінії згину для подальшого складання коробки.',
     ARRAY['box_blank'],
     ARRAY['coated_400','coated_350','coated_320','coated_300','coated_250','coated_170','coated_160',
           'coated_150','coated_130','coated_115'],
     '{"duration_hours_per_1000_sheets": 0.3}',
     'заготовка з лініями згину', NULL, NULL),

    ('corner_taping',
     'Обклейка кутиків', 8,
     'Обклейка кутиків жорсткої коробки скотчем для фіксації.',
     ARRAY['rigid_box'], NULL,
     '{"duration_hours_per_1000_units": 0.35}',
     'коробка з закріпленими кутами', NULL, NULL),

    ('box_assembly',
     'Обклейка / складання коробки', 8,
     'Обклейка коробки друкарським листом; машина для склеювання картонних коробок; формування готового короба.',
     ARRAY['rigid_box','folding_box'],
     NULL,
     '{"duration_hours_per_1000_units": 3.0}',
     'готова коробка', NULL, NULL),

    ('blank_stripping',
     'Витруска облою', 8,
     'Видалення непотрібного матеріалу (облою) після висічки.',
     ARRAY['rigid_box','folding_box','box_blank'], NULL,
     '{"duration_hours_per_1000_sheets": 0.25}',
     'чиста заготовка без облою', NULL, NULL),

    ('card_cutting',
     'Карткова машина (різання на колоди / листівки)', 7,
     'Порізка друкарських листів на колоди карт або на листівки інформаційні — той самий цеховий вузол (карткова лінія). Обов''язкова наявність карткової машини (наприклад MT-1040). За потреби — закруглення кутів R3/R4 на окремому вузлі.',
     ARRAY['card_deck','info_leaflet'],
     ARRAY['playing_card_310','coated_350','coated_320','coated_300','coated_250','coated_170','coated_160',
           'coated_150','coated_130','coated_115','coated_90',
           'offset_120','offset_250'],
     '{"duration_hours_per_1000_cards": 0.2}',
     'готові колоди карт', NULL, NULL),

    ('rulebook_final_cutting',
     'Порізка інструкції на кінцевий формат', 3,
     'Порізка надрукованого матеріалу на формат готової інструкції (після друку; окремий етап від порізки під формат машини).',
     ARRAY['rulebook_thin','rulebook_thick'],
     ARRAY['offset_90','offset_120','offset_250','coated_115','coated_90','coated_130','coated_150'],
     '{"duration_hours_per_1000_sheets": 0.12}',
     'аркуші/зошити у форматі інструкції', NULL, NULL),

    ('rulebook_folding_creasing',
     'Фальцування / бігування (інструкція)', 6,
     'Фальцування вручну або бігування (канавки) на тигелі — залежно від товщини та типу паперу; підготовка до скоби або клеєвого корінця.',
     ARRAY['rulebook_thin','rulebook_thick'],
     ARRAY['offset_90','offset_120','offset_250','coated_115','coated_90','coated_130','coated_150'],
     '{"duration_hours_per_1000_units": 0.45}',
     'зошит з лініями згину / відфальцьовані аркуші', NULL, NULL),

    ('saddle_stitching',
     'Кріплення скобою (садл-стітч)', 7,
     'Зшивання металевою скобою по корінцю — застосовується для брошурованих інструкцій з кількома сторінками, коли це передбачає замовник.',
     ARRAY['rulebook_thin'],
     ARRAY['offset_90','offset_120','offset_250','coated_115','coated_90','coated_130','coated_150'],
     '{"duration_hours_per_1000_units": 0.5}',
     'готова брошура', NULL, NULL),

    ('perfect_binding',
     'Клейове скріплення (perfect binding)', 7,
     'Клеєне скріплення аркушів по корінцю — для товстих правил / книгових блоків.',
     ARRAY['rulebook_thick'],
     ARRAY['offset_90','offset_120','offset_250','coated_115','coated_90','coated_130','coated_150'],
     '{"duration_hours_per_1000_units": 1.0}',
     'готова книга', NULL, NULL),

    ('game_board_hand_wrapping',
     'Обклейка ігрового поля вручну', 8,
     'Ручна обклейка ігрового поля (палітурна основа з друкованим покриттям) після каширування та висічки; доведення якості обкладинки.',
     ARRAY['game_board'], NULL,
     '{"duration_hours_per_1000_units": 3.5}',
     'поле після ручної обклейки', NULL, NULL),

    ('forzats_tipping',
     'Наклейка форзацу', 8,
     'Наклеювання форзацу на блок ігрового поля за специфікацією макету.',
     ARRAY['game_board'], NULL,
     '{"duration_hours_per_1000_units": 0.55}',
     'поле з форзацем', NULL, NULL),

    ('game_board_platen_scoring',
     'Рицовка поля (на тигелі)', 6,
     'Проріз (канавка) палітурного картону на тигельному пресі для ліній згину поля.',
     ARRAY['game_board'], NULL,
     '{"duration_hours_per_1000_sheets": 0.35}',
     'поле з рицованими лініями', NULL, NULL),

    ('game_board_platen_creasing',
     'Бігування поля (на тигелі)', 6,
     'Бігування ліній згину на тигельному пресі для складання поля за макетом.',
     ARRAY['game_board'], NULL,
     '{"duration_hours_per_1000_sheets": 0.3}',
     'поле після бігування', NULL, NULL),

    ('game_kit_assembly',
     'Комплектація гри', 10,
     'Збір комплектуючих і вкладання в коробку.',
     ARRAY['rigid_box','all'], NULL,
     '{"duration_hours_per_1000_units": 1.5}',
     'скомплектований продукт', NULL, NULL),

    ('shrink_wrapping',
     'Термоупакування', 11,
     'Термоусадкова плівка на готовий продукт.',
     ARRAY['all'], NULL,
     '{"duration_hours_per_1000_units": 0.35}',
     'термопакований продукт', NULL, NULL),

    ('shipper_packing',
     'Пакування в гофроящики', 12,
     'Пакування в гофротару (ящики) для транспортування.',
     ARRAY['all'], NULL,
     '{"duration_hours_per_1000_units": 0.3}',
     'продукт у транспортній тарі', NULL, NULL),

    ('palletizing',
     'Палетування', 13,
     'Формування палети, стягування, маркування перед відвантаженням.',
     ARRAY['all'], NULL,
     '{"duration_hours_per_1000_units": 0.2}',
     'палета готова до відвантаження', NULL, NULL),

    ('quality_control',
     'Контроль якості', 9,
     'Візуальна та інструментальна перевірка відповідності готової продукції.',
     ARRAY['all'], NULL,
     '{"duration_hours_per_1000_units": 0.5}',
     'верифікований продукт', NULL, NULL),

    ('packaging',
     'Пакування (агреговане)', 10,
     'Загальне фінальне пакування та підготовка до відвантаження, якщо маршрут не розбитий на термоупакування / ящики / палети.',
     ARRAY['all'], NULL,
     '{"duration_hours_per_1000_units": 0.3}',
     'готове замовлення', NULL, NULL);
